#pragma once

#define SCREEN_WIDTH 600 
#define SCREEN_HEIGHT 600
#define SCREEN_CENTER CLITERAL(Vector2){SCREEN_WIDTH / 2.0, SCREEN_HEIGHT / 2.0}
#define SCREEN_AREA CLITERAL(Rectangle){0, 0, SCREEN_WIDTH, SCREEN_HEIGHT}
#define NEARBLACK CLITERAL(Color){15, 15, 15, 255}

#define ASTEROID_MAX 8
#define ASTEROID_RANDOM_ANGLE 20 * DEG2RAD
#define ASTEROID_SPLIT_ANGLE 80 * DEG2RAD
#define ASTEROID_DELAY 2.25f

#define PLAYERS_MAX 8

#define PROJECTILE_MAX 4

#define SERVER "10.3.72.33"
#define PORT 5150

#define BUFLEN 1024
